feat(cli): support https for devServer
myNameIsDu/aktiv pull request #65
Opened 2022-01-12 16:45 UTC by bigbigDreamer

feat(cli): support https for devServer

2022-01-12 16:51 UTC, myNameIsDu commented
need to rebase

2022-01-12 16:57 UTC, bigbigDreamer commented
> need to rebase

done

2022-01-14 03:20 UTC, myNameIsDu requested changes

2022-01-14 03:20 UTC, myNameIsDu commented on packages/cli/utils/createCaCertificate.js
> +    static CA_CERT_DOMAIN_CACHE_LIST_FILE_NAME = 'akCertDomain.json';
是不是不用叫json, 因为上边不是写的json格式

2022-01-14 03:20 UTC, myNameIsDu commented on packages/cli/utils/createCaCertificate.js
> +        return this.WIPDomain.indexOf(domain) > -1;
可以使用include

2022-01-14 03:20 UTC, myNameIsDu commented on packages/cli/utils/createCaCertificate.js
> +                return 0;
这里为什么 return 0 呢

2022-01-14 03:20 UTC, myNameIsDu commented on packages/cli/utils/createCaCertificate.js
> +        }
这里是不是有些问题，每次生成的证书都是同样的名字，但是却把domain加入到了list里边，判断是existed的，就不在生成证书了

2022-01-14 03:20 UTC, myNameIsDu commented
need test case

2022-01-14 03:35 UTC, myNameIsDu requested changes

2022-01-14 03:35 UTC, myNameIsDu commented on packages/cli/utils/createCaCertificate.js
> +        this.createLocalCA();
可以不用每次都使用install 可以看这个
![image](https://user-images.githubusercontent.com/53305259/149447160-694b1215-4afa-4baa-9f32-c4dec991de46.png)

2022-01-14 07:08 UTC, bigbigDreamer commented on packages/cli/tsconfig.json
> +    ]
这个文件里给我爆大量的 ts 错误，蛋疼的要死

2022-01-14 07:57 UTC, myNameIsDu commented on packages/cli/tsconfig.json
> +    ]
我拉下来看看

2022-01-14 09:40 UTC, bigbigDreamer commented on packages/cli/utils/createCaCertificate.js
> +    static CA_CERT_DOMAIN_CACHE_LIST_FILE_NAME = 'akCertDomain.json';
这个无所谓了，不过 fs读取json 的输出流直接是字符串，还没试过别的

2022-01-14 09:40 UTC, bigbigDreamer commented on packages/cli/utils/createCaCertificate.js
> +        return this.WIPDomain.indexOf(domain) > -1;
那是 es 7 的语法了，这个工具型的，就先 es5/6优先吧，有些棒槌node 没那么高

2022-01-14 09:42 UTC, bigbigDreamer commented on packages/cli/bin/ak-dev.js
> +                          },
https 不是 server.options的 的属性
<img width="801" alt="image" src="https://user-images.githubusercontent.com/39019913/149494100-50a97aad-0697-4ec0-872f-64a4f81b63c7.png">

2022-01-14 09:42 UTC, myNameIsDu commented on packages/cli/utils/createCaCertificate.js
> +    static CA_CERT_DOMAIN_CACHE_LIST_FILE_NAME = 'akCertDomain.json';
是的，fs读取没问题，区别在于require直接支持读取json,我们是否可以存一个json，domain为key，ca 和 key为value，这样就能解决下面那个问题，也能解决多域名缓存的问题

2022-01-14 09:42 UTC, bigbigDreamer commented on packages/cli/utils/createCaCertificate.js
> +        }
确实有点问题，我改下

2022-01-14 09:43 UTC, bigbigDreamer commented on packages/cli/utils/createCaCertificate.js
> +                return 0;
return 0 表示程序正常退出终止，跟 return 的意思一样。问题不大

2022-01-14 09:43 UTC, myNameIsDu commented on packages/cli/utils/createCaCertificate.js
> +        return this.WIPDomain.indexOf(domain) > -1;
ok

2022-01-14 09:45 UTC, myNameIsDu commented on packages/cli/bin/ak-dev.js
> +                          },
我的意思是deveServe.https 支持是一个object 的
![image](https://user-images.githubusercontent.com/53305259/149494558-f8398af5-f724-4784-9f08-241581eb16e0.png)

2022-01-14 09:49 UTC, bigbigDreamer commented on packages/cli/bin/ak-dev.js
> +                          },
giao ，还是听你的吧，直接废弃 https，，mmp，太蛋疼了

2022-01-15 10:17 UTC, myNameIsDu approved these changes

2022-01-15 11:12 UTC, bigbigDreamer commented
> need test case

later

2022-01-15 11:12 UTC, merged